#
# gp-docker-image-cleanup
# Copyright (c) 2023, OSkey SAS. All rights reserved.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: gp-devenv/gp-docker-image-cleanup
author: Greg PFISTER
description: Github action to cleanup Docker images hosted on Github
branding:
    color: red
    icon: trash
inputs:
    runAsUser:
        description: User who will be used to interact with ghcr.io API
        required: true
    token:
        description: Github token for the runAsUser
        required: false
        default: ${{ github.token }}
    package:
        description: Package name (<owner>/<name>), when not the same as the repository
        required: false
    isOwnedByOrganization:
        description: Is this package owned by an isOrganization ?
        required: false
        default: 'false'
    retentionDays:
        description: Retain image for this many days
        required: false
        default: '30'

runs:
    using: 'node16'
    main: 'dist/index.js'
