#
# gp-docker-image-cleanup
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

version: '3.9'

# Services
services:
    gp-docker-image-cleanup:
        container_name: gp-docker-image-cleanup
        user: vscode
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ..:/workspace
            - gp-docker-image-cleanup-devenv-home:/home
        networks:
            - gp-docker-image-cleanup-devenv-net

volumes:
    gp-docker-image-cleanup-devenv-home:
        name: gp-docker-image-cleanup-devenv-home

networks:
    gp-docker-image-cleanup-devenv-net:
        name: gp-docker-image-cleanup-devenv-net
