#!/bin/sh

# NVM
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

echo "Linting ./src"
npm run lint || exit 1

#echo "Linting ./test"
#npm run lint:test || exit 1

echo "Rebuilding"
npm run build && git add dist/index.js

